chore(deploy): upload change that triggers failure to test deploy fallback

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,11 +36,13 @@ jobs:
             chmod +x doDeploy.sh
             bash doDeploy.sh
 
-      - name: Wait for services and run smoke tests
-        run: |
-          sleep 30
-          curl --fail --silent --max-time 10 https://todo.federicopacheco.dev/api/health
-          curl --fail --silent --max-time 10 https://todo.federicopacheco.dev
+      # - name: Run smoke tests
+      #   run: |
+      #     curl --fail --silent --max-time 15 https://todo.federicopacheco.dev/api/health
+      #     curl --fail --silent --max-time 15 https://todo.federicopacheco.dev
+
+      - name: Fail on purpose to trigger rollback
+        run: exit 1
 
       - name: Deployment successful
         if: success()
